### ISSUE TITLE
Mean: Share and Balance Main Checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#1]
# Mean: Share and Balance main checklist

## Design
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback** 
   ~- [ ] *If a Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)~
   - [x] *If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-prototype items**
  - [x] Auxilary screenshots (at least 1 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [x] Email/Twitter announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [x] **Post-publication items**
  - [x] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Create "sim primer" issue
  - [x] Hold postmortem if applicable (Date: n/a)

## Inclusive Features
- [x] Alternative Input (Started: ) (Completed: ) 
- [x] Pan & Zoom
- [x] Sound & Sonification (UI)
- [x] Sound & Sonification (Pedagogical) - (include link to relevant sonification design document)
    - [x] Sound design complete (Started: ) (Completed: ) 
    - [x] Development complete (Started: ) (Completed: ) 

~- [ ] Interactive Description - (link to description design & implementation checklist)~
    ~- [ ] Description design complete (Started: ) (Completed: )~
    ~- [ ] Development complete (Started: ) (Completed: )~
    ~- [ ] Mobile description included~
~- [ ] Voicing - (include links to relevant voicing design document)~

## Implementation
- [x] **Repository created** by following [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md) (Date: 3/31/2022)
- [x] **Development started** (Date: 4/1/2022)
- [x] **Sim is "feature complete"** (Date: //)
- [x] **QA team "first look"** (Date: //)
- [x] Interviews may happen around here (see above)
- [x] **Code review checklist completed"** (Date: //)
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Sim dev test completed** (Date: //)
- [x] **Sim RC tests completed** (Date: //)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/master/js/CreditsNode.js))
 ~- [ ] Add CT tests for public query parameters~
- [x] **Published** (Date: 8/27/24)

## QA
~~- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo~~
- [x] **Dev testing started** (Date: //)
- [x] **Dev testing completed** (Date: //)
- [x] **First RC published** (Date: //)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: //)

**Comment by amanda-phet** [comment]
Assigned to @marlitas because of the one unchecked thing about CT.

**Comment by marlitas** [comment]
There are no sim specific public query parameters. Closing
