### ISSUE TITLE
Polish checklist

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#232]
- [x] Move the controls (checkboxes and scene selection buttons) down about 7.5 px or so to align with the top of the notepad. I find the current alignment just a bit odd. 
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/59324b93-d718-4ae8-b82a-268d3bd42701)

- [ ] #267
- [x] The drawn "plate" and the bars seem off-center. Not sure which one needs to shift. 
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/08351edc-194c-482d-9d32-b32a315520a5)

- [x] Balance Point screen dialog: add an additional representation of the mean as a mixed number before the decimal. 
- [x] Balance Point screen dialog: For the rounded mean value, use the "approximately equal" symbol ≈
- [x] Expand the dialog dimensions vertically a few pixels. On some machines, and at a close zoom, you can slightly see the rings and pages. 
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/e1b317b2-5558-4386-bc3f-556f1685a60c)
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/b6406fc9-e847-49ce-972b-f9b8358b4f03)

- [x] Put a semi-transparent white background on the total on all screens. I think 50% opacity works, but we could maybe go higher if it doesn't look good in context.
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/e66a5a3c-5a2b-44f4-9fa9-b049a125c903)

**Comment by marlitas** [comment]
Everything here is done except for making the circles and balance beam in Balance Point "sketchy" I will need new artwork for that. Over to @amanda-phet.

**Comment by amanda-phet** [comment]
These all look great. I converted the last one into an issue so we can close this!
